import json
import os
import boto3
import requests
import base64
import logging
from datetime import datetime

logger = logging.getLogger()
logger.setLevel(logging.INFO)

secretsmanager = boto3.client('secretsmanager')


def get_github_token():
    secret = secretsmanager.get_secret_value(
        SecretId=os.environ['GITHUB_TOKEN_SECRET']
    )
    return json.loads(secret['SecretString'])['token']


def render_terraform(db_name: str, engine: str, environment: str) -> str:
    """Generate the Terraform file content for a new RDS instance."""
    return f'''# Auto-generated by RDS Provisioner Lambda
# Created: {datetime.utcnow().isoformat()}

module "rds_{db_name}_{environment}" {{
  source = "../../modules/rds"

  db_name     = "{db_name}"
  engine      = "{engine}"
  environment = "{environment}"

  vpc_id     = var.vpc_id
  subnet_ids = var.subnet_ids

  allowed_cidr_blocks = var.allowed_cidr_blocks
}}
'''


def create_github_pr(token: str, db_name: str, engine: str, environment: str):
    owner   = os.environ['GITHUB_OWNER']
    repo    = os.environ['GITHUB_REPO']
    base    = os.environ['GITHUB_BASE_BRANCH']
    headers = {
        'Authorization': f'token {token}',
        'Accept': 'application/vnd.github.v3+json'
    }
    base_url = f'https://api.github.com/repos/{owner}/{repo}'

    # 1. Get base branch SHA
    ref_resp = requests.get(f'{base_url}/git/ref/heads/{base}', headers=headers)
    ref_resp.raise_for_status()
    base_sha = ref_resp.json()['object']['sha']
    logger.info(f"Base branch SHA: {base_sha}")

    # 2. Create new branch
    branch_name = f'provision/{environment}-{db_name}-{datetime.utcnow().strftime("%Y%m%d%H%M%S")}'
    requests.post(f'{base_url}/git/refs', headers=headers, json={
        'ref': f'refs/heads/{branch_name}',
        'sha': base_sha
    }).raise_for_status()
    logger.info(f"Created branch: {branch_name}")

    # 3. Create the Terraform file on the new branch
    tf_content = render_terraform(db_name, engine, environment)
    file_path  = f'environments/{environment}/{db_name}.tf'
    encoded    = base64.b64encode(tf_content.encode()).decode()

    requests.put(
        f'{base_url}/contents/{file_path}',
        headers=headers,
        json={
            'message': f'feat: provision {environment} {engine} RDS for {db_name}',
            'content': encoded,
            'branch':  branch_name
        }
    ).raise_for_status()
    logger.info(f"Created file: {file_path}")

    # 4. Open the Pull Request
    pr_resp = requests.post(
        f'{base_url}/pulls',
        headers=headers,
        json={
            'title': f'[RDS] Provision {environment} {engine} database: {db_name}',
            'body':  (
                f'## Auto-generated RDS Provision Request\n\n'
                f'| Field | Value |\n'
                f'|-------|-------|\n'
                f'| Database Name | `{db_name}` |\n'
                f'| Engine | `{engine}` |\n'
                f'| Environment | `{environment}` |\n\n'
                f'> Merge this PR to trigger the CircleCI pipeline and provision the RDS instance.'
            ),
            'head': branch_name,
            'base': base
        }
    )
    pr_resp.raise_for_status()
    pr_url = pr_resp.json()['html_url']
    logger.info(f"PR created: {pr_url}")
    return pr_url


def lambda_handler(event, context):
    for record in event['Records']:
        # SQS wraps SNS which wraps the original JSON body
        outer  = json.loads(record['body'])
        payload = json.loads(outer.get('Message', record['body']))

        db_name     = payload['db_name']
        engine      = payload['engine']
        environment = payload['environment']

        logger.info(f"Processing request: {db_name} / {engine} / {environment}")

        token  = get_github_token()
        pr_url = create_github_pr(token, db_name, engine, environment)

        logger.info(f"Done! PR: {pr_url}")

    return {'statusCode': 200, 'body': 'OK'}